### ISSUE TITLE
InstallationError: xo-web leads to "TypeError: Cannot assign to read only property '$methodName' of false"

### ISSUE THREAD

**Issue by innoreq** [vatesfr/xo#41]
I followed exactly the installation procedure, but when issueing the "gulp --production" command, this leads to this error - any idea how to fix that?
`
[11:34:53] Finished 'copyAssets' after 5.07 s
/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:330
    target.$methodName = method.name;
                       ^
TypeError: Cannot assign to read only property '$methodName' of false
  at matchRegular (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:330:24)
  at match (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:36:66)
  at traverse.post (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:995:23)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:50:13)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:44:21)
  at visit (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:41:25)
  at traverse (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/node_modules/ordered-ast-traverse/ordered-ast-traverse.js:54:5)
  at ngAnnotate (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/ng-annotate/build/es5/ng-annotate-main.js:989:5)
  at Transform._transform (/root/xo-web/node_modules/gulp-ng-annotate/index.js:28:15)
  at Transform._read (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at Transform._write (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at Transform.Writable.write (/root/xo-web/node_modules/gulp-ng-annotate/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at PassThrough.ondata (_stream_readable.js:540:20)
  at PassThrough.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at PassThrough.Readable.push (_stream_readable.js:126:10)
  at PassThrough.Transform.push (_stream_transform.js:140:32)
  at afterTransform (_stream_transform.js:96:12)
  at TransformState.afterTransform (_stream_transform.js:74:12)
  at PassThrough._transform (_stream_passthrough.js:40:3)
  at PassThrough.Transform._read (_stream_transform.js:179:10)
  at PassThrough.Transform._write (_stream_transform.js:167:12)
  at doWrite (_stream_writable.js:301:12)
  at writeOrBuffer (_stream_writable.js:288:5)
  at PassThrough.Writable.write (_stream_writable.js:217:11)
  at PassThrough.Writable.end (_stream_writable.js:449:10)
  at onBundleComplete (/root/xo-web/gulpfile.js:112:7)
  at /root/xo-web/node_modules/browserify/index.js:686:13
  at ConcatStream.<anonymous> (/root/xo-web/node_modules/browserify/node_modules/concat-stream/index.js:32:43)
  at ConcatStream.emit (events.js:129:20)
  at finishMaybe (/root/xo-web/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:460:14)
  at endWritable (/root/xo-web/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:469:3)
  at ConcatStream.Writable.end (/root/xo-web/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:436:5)
  at Labeled.onend (/root/xo-web/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:537:10)
  at Labeled.g (events.js:199:16)
  at Labeled.emit (events.js:129:20)
  at /root/xo-web/node_modules/browserify/node_modules/labeled-stream-splicer/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:934:16
  at process._tickCallback (node.js:355:11)
`

**Comment by olivierlambert** [comment]
Hi!

Please wait before we merge `next-release` branch in `master` for `xo-web`! (done for `xo-server` but not yet here).

Should be done Monday at worst. We'll also update the documentation accordingly.

Also pinging @julien-f about that (in charge of that stuff)

**Comment by innoreq** [comment]
Wow, that was fast... any workaround that I could apply immediately?

**Comment by olivierlambert** [comment]
Switch to `next-release` for `xo-web`, with a `git checkout next-release`.

Then after the `npm -i`, please use `npm run build` in the root folder of `xo-web`. And that's it!

**Comment by innoreq** [comment]
Great, it works now! Thanks a lot!

**Comment by innoreq** [comment]
Ou: merçi beaucoup ;-)

**Comment by olivierlambert** [comment]
\o/
