### ISSUE TITLE
xo-server fails to start after updating to 4.0.2 with xoa-updater

### ISSUE THREAD

**Issue by danielknell** [vatesfr/xo#54]
```
root@xoa:~# xoa-updater --upgrade
Successfully connected to xoa-updater-service
Checking new versions...ok ✔
New packages available:
  xo-server 4.0.2
  xo-web-free 4.0.2
Downloading packages...
  xo-web-free .................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................. ok ✔
  xo-server ....................................................................................................................................................................................... ok ✔
Installing new packages...
  xo-web-free ✔
  xo-server ✔
xo-server will be restarted...
Restarting xo-server ✔

✔ Your XOA has been successfully upgraded.

```
update seemed to run successfully
```
root@xoa:~# xoa-updater
Successfully connected to xoa-updater-service
Checking new versions...ok ✔

ℹ All up to date

```
everythings upto date, but the servers not responding
```
root@xoa:~# systemctl restart xo-server.service
```
still not working...
```
root@xoa:~# systemctl status xo-server.service
xo-server.service - XO Server
   Loaded: loaded (/etc/systemd/system/xo-server.service; enabled)
   Active: failed (Result: start-limit) since Sun 2015-06-07 04:20:58 CEST; 12s ago
  Process: 6414 ExecStart=/usr/local/bin/xo-server (code=exited, status=1/FAILURE)

Jun 07 04:20:58 xoa systemd[1]: Unit xo-server.service entered failed state.
Jun 07 04:20:58 xoa systemd[1]: xo-server.service holdoff time over, schedu...t.
Jun 07 04:20:58 xoa systemd[1]: Stopping XO Server...
Jun 07 04:20:58 xoa systemd[1]: Starting XO Server...
Jun 07 04:20:58 xoa systemd[1]: xo-server.service start request repeated to...t.
Jun 07 04:20:58 xoa systemd[1]: Failed to start XO Server.
Jun 07 04:20:58 xoa systemd[1]: Unit xo-server.service entered failed state.
```
trying to start the server manually...
```
root@xoa:~# /usr/local/bin/xo-server
  xo:main Configuration loaded. +0ms
✖ Cannot read property 'http' of undefined
TypeError: Cannot read property 'http' of undefined
    at main$ (/source/index.js:391:27)
    at tryCatch (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at /usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:165:16
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
From previous event:
    at execPromise (/usr/local/lib/node_modules/xo-server/node_modules/exec-promise/index.js:59:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/xo-server/bin/xo-server:7:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
root@xoa:~# vi /etc/systemd/system/xo-server.service
root@xoa:~# /usr/local/bin/xo-server
  xo:main Configuration loaded. +0ms
✖ Cannot read property 'http' of undefined
TypeError: Cannot read property 'http' of undefined
    at main$ (/source/index.js:391:27)
    at tryCatch (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at invoke (/usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at /usr/local/lib/node_modules/xo-server/node_modules/babel-runtime/regenerator/runtime.js:165:16
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
From previous event:
    at execPromise (/usr/local/lib/node_modules/xo-server/node_modules/exec-promise/index.js:59:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/xo-server/bin/xo-server:7:24)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by olivierlambert** [comment]
Hi,

Thanks for your report.

Are you behind a proxy or a firewall? It seems the build process could fail if it's the case, that's why we'll release both new version of the updater and xo-server to tackle those situations.

**Comment by danielknell** [comment]
no outbound firewalls, only inbound.

**Comment by olivierlambert** [comment]
Okay, stay tuned with a new update coming soon.

**Comment by olivierlambert** [comment]
@danielknell : we just pushed a new patch for `xo-server` (4.0.3), you should see it with:

` xoa-updater --upgrade`

If `xo-server` is not started automatically, do a:

`systemctl restart xo-server.service`

**Comment by danielknell** [comment]
:+1:
