### ISSUE TITLE
Unable to login after fresh manual installation

### ISSUE THREAD

**Issue by Phlogi** [vatesfr/xo#55]
Installed as documented in the manual, however I can't login with admin@admin.net / admin: 

```
> xo-server@4.0.3 start /opt/xo_orchestra/xo-server
> node bin/xo-server

  app-conf /opt/xo_orchestra/xo-server/.xo-server.yaml +0ms
  xo:main Configuration loaded. +9ms
  xo:main Web server listening on http://[::]:80 +9ms
  xo:main Setting up / → /opt/xo_orchestra/xo-web/dist +242ms
  xo:perf blocked for 178ms +2ms
  xo:main - WebSocket connection +1m
  xo:main + WebSocket connection +10s
  xo:main + WebSocket connection +22s
  xo:api session.signOut(...) +15s
  xo:api session.signInWithPassword(...) +4ms
use session.signIn() instead
Error: unsupported algorithm
    at verify (/opt/xo_orchestra/xo-server/node_modules/hashy/index.js:216:9)
From previous event:
    at asyncWrapper (/opt/xo_orchestra/xo-server/node_modules/hashy/index.js:102:24)
    at User.checkPassword$ (/source/models/user.js:22:47)
    at tryCatch (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/                                                     runtime.js:100:21)
    at invoke (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
    at enqueueResult (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:167:17)
    at Promise.exp (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/$.def.js:38:36)
    at AsyncIterator.enqueue (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:166:16)
    at AsyncIterator.prototype.(anonymous function) [as next] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:10                                                     0:21)
    at Object.runtime.async (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:192:12)
    at User.checkPassword (/source/models/user.js:20:15)
    at passwordAuthenticationProvider$ (/source/index.js:335:54)
    at tryCatch (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/                                                     runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
  xo:api Error: session.signInWithPassword(...) → InvalidCredential: invalid credential +8ms
  xo:main - WebSocket connection +6s
```

**Comment by julien-f** [comment]
Thank you for your report, I am on it.

**Comment by julien-f** [comment]
A new version of hashy as been released to fix the issue, rerun `npm install` and it should work.

**Comment by julien-f** [comment]
It may be necessary to force the update of this dependency with `npm install hashy@latest`.

**Comment by Phlogi** [comment]
Simply running npm install in the xo-server directory did not fix it yet, however  
```
npm install hashy@latest 
```
did.  It works now, thanks!
