### ISSUE TITLE
Upgrade to 4.4.0: application doesn't load properly in browser, no content

### ISSUE THREAD

**Issue by Phlogi** [vatesfr/xo#66]
I can only see the menu bar on top, when I try to logout or start a new session, it doesn't show me the login screen. Here is the log output:

```
Thu, 10 Sep 2015 14:37:59 GMT xo:api session.signInWithPassword(...) [1ms] =!> InvalidParameters: invalid parameter(s)
InvalidParameters: invalid parameter(s)
    at checkParams (/source/api.js:64:11)
    at Api.call$ (/source/api.js:293:7)
    at tryCatch (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:67:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:294:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:100:21)
    at GeneratorFunctionPrototype.invoke (/opt/xo_orchestra/xo-server/node_modules/babel-runtime/regenerator/runtime.js:136:37)
```

**Comment by Phlogi** [comment]
This is the build output: http://pastebin.com/41sB5iFk

**Comment by julien-f** [comment]
It seems you have very old npm deps, try reinstalling them:

```
> rm -fr node_modules
> npm install
```

**Comment by julien-f** [comment]
Any news?

**Comment by Phlogi** [comment]
Well it fails on several dependencies later on...

**Comment by Phlogi** [comment]
```
[17:46:58] 'buildScripts' errored after 6 s
[17:46:58] Error: Cannot find module 'angular-natural-sort' from '/opt/xo_orchestra/xo-web/app'
  at /opt/xo_orchestra/xo-web/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
  at process (/opt/xo_orchestra/xo-web/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
  at ondir (/opt/xo_orchestra/xo-web/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
  at load (/opt/xo_orchestra/xo-web/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
  at onex (/opt/xo_orchestra/xo-web/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
  at /opt/xo_orchestra/xo-web/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
  at FSReqWrap.oncomplete (fs.js:95:15)

Also I can't instlal this module manually, npm doesn't find it.

**Comment by Phlogi** [comment]
Nevermind, I figured out it was related to a low memory issue - the build process got killed due to that. I started over from scratch and it works now! Sorry for wasting your time and thanks for the great support.

**Comment by olivierlambert** [comment]
No problem @Phlogi . Happy to see it working :)
