### ISSUE TITLE
Manual install: How can the plugins be built?

### ISSUE THREAD

**Issue by Phlogi** [vatesfr/xo#71]
Well, I guess the title says it - I can't seem to find the email plugin on a manual build. Is that intentional?

**Comment by julien-f** [comment]
Not at all, we need to update the documentation.

You can find the plugin [there](https://github.com/vatesfr/xo-server-transport-email).

**Comment by Phlogi** [comment]
Perfect, thank you - and the idea is to install those globally, i.e.: npm install --global xo-server-transport-email?

**Comment by julien-f** [comment]
If your xo-server is also installed globally, otherwise, clone the repository and build the project yourself in xo-server's `node_modules/`.

**Comment by Phlogi** [comment]
I installed it in my xo-server and after npm install xo-server-transport-email in that directory I can see it under node_modules, however the server does not list it under plugins. Anything else than restarting the server? Rebuilding it?

**Comment by olivierlambert** [comment]
Adding the plugin, as explained in the doc: https://xen-orchestra.com/docs/backups.html#email-notifications (last line)

**Comment by Phlogi** [comment]
Is any plugin configuration needed? I get an error when configuring the plugin:

 | plugin.load(...) [12ms] =!> InvalidParameters: invalid parameter(s)

**Comment by Phlogi** [comment]
![image](https://cloud.githubusercontent.com/assets/6451003/11559244/9200c3c6-99b7-11e5-93aa-1b51f817f47e.png)

error message in GUI

**Comment by julien-f** [comment]
Do you have any error in the browser console?

**Comment by Phlogi** [comment]
Yes, sorry I forgot to check that:

```
Error for plugin.load: JsonRpcError {code: -32602, data: "plugin not configured", message: "invalid parameter(s)", name: "JsonRpcError", stack: "JsonRpcError: invalid parameter(s)↵    at JsonRpcS…:20680)↵    at https://xen.serveraddress/app.js:31:22388"…}__stackCleaned__: truecode: -32602data: "plugin not configured"isOperational: truemessage: "invalid parameter(s)"name: "JsonRpcError"stack: "JsonRpcError: invalid parameter(s)↵    at JsonRpcServer.<anonymous> (https://xen.serveraddress/app.js:72:1549)↵    at JsonRpcServer._write (https://xen.serveraddress/app.js:72:519)↵    at doWrite (https://xen.serveraddress/app.js:68:27050)↵    at writeOrBuffer (https://xen.serveraddress/app.js:68:26822)↵    at JsonRpcServer.Writable.write (https://xen.serveraddress/app.js:68:29990)↵    at WebSocket.<anonymous> (https://xen.serveraddress/app.js:71:27413)↵From previous event:↵    at JsonRpcServer.<anonymous> (https://xen.serveraddress/app.js:72:2005)↵From previous event:↵    at https://xen.serveraddress/app.js:71:27777↵From previous event:↵    at Api.call (https://xen.serveraddress/app.js:71:27746)↵    at Xo.<anonymous> (https://xen.serveraddress/app.js:72:24578)↵    at Scope.$eval (https://xen.serveraddress/app.js:28:5228)↵    at Scope.$digest (https://xen.serveraddress/app.js:28:3042)↵    at Scope.$apply (https://xen.serveraddress/app.js:28:5646)↵    at $$debounceViewValueCommit (https://xen.serveraddress/app.js:31:22365)↵    at $setViewValue (https://xen.serveraddress/app.js:31:21821)↵    at HTMLInputElement.listener (https://xen.serveraddress/app.js:29:9081)↵    at HTMLInputElement.jQuery.event.dispatch (https://xen.serveraddress/app.js:56:11101)↵    at HTMLInputElement.elemData.handle (https://xen.serveraddress/app.js:56:5931)↵From previous event:↵    at Xo.call (https://xen.serveraddress/app.js:72:24545)↵    at Object.defineProperties.call (https://xen.serveraddress/app.js:12:29849)↵    at Object.load (https://xen.serveraddress/app.js:14:7086)↵    at _execPluginMethod (https://xen.serveraddress/app.js:7:18936)↵    at toggleLoad (https://xen.serveraddress/app.js:7:19792)↵    at fn (eval at <anonymous> (https://xen.serveraddress/app.js:30:14292), <anonymous>:4:316)↵    at Scope.$eval (https://xen.serveraddress/app.js:28:5228)↵    at https://xen.serveraddress/app.js:31:10910↵    at https://xen.serveraddress/app.js:31:21657↵    at forEach (https://xen.serveraddress/app.js:24:1084)↵    at $$writeModelToScope (https://xen.serveraddress/app.js:31:21600)↵    at writeToModelIfNeeded (https://xen.serveraddress/app.js:31:20810)↵    at https://xen.serveraddress/app.js:31:21501↵    at validationDone (https://xen.serveraddress/app.js:31:20212)↵    at processAsyncValidators (https://xen.serveraddress/app.js:31:19998)↵    at $$runValidators (https://xen.serveraddress/app.js:31:20366)↵    at $$parseAndValidate (https://xen.serveraddress/app.js:31:21363)↵    at $commitViewValue (https://xen.serveraddress/app.js:31:20680)↵    at https://xen.serveraddress/app.js:31:22388"__proto__: JsonRpcError(anonymous function) @ app.js:14tryCatcher @ app.js:37Promise._settlePromiseFromHandler @ app.js:35Promise._settlePromiseAt @ app.js:35Promise._settlePromises @ app.js:36(anonymous function) @ app.js:34Scope.$eval @ app.js:28Scope.$digest @ app.js:28(anonymous function) @ app.js:28completeOutstandingRequest @ app.js:25(anonymous function) @ app.js:25
app.js:34 Unhandled rejection JsonRpcError: invalid parameter(s)
    at JsonRpcServer.<anonymous> (https://xen.serveraddress/app.js:72:1549)
    at JsonRpcServer._write (https://xen.serveraddress/app.js:72:519)
    at doWrite (https://xen.serveraddress/app.js:68:27050)
    at writeOrBuffer (https://xen.serveraddress/app.js:68:26822)
    at JsonRpcServer.Writable.write (https://xen.serveraddress/app.js:68:29990)
    at WebSocket.<anonymous> (https://xen.serveraddress/app.js:71:27413)
From previous event:
    at JsonRpcServer.<anonymous> (https://xen.serveraddress/app.js:72:2005)
From previous event:
    at https://xen.serveraddress/app.js:71:27777
From previous event:
    at Api.call (https://xen.serveraddress/app.js:71:27746)
    at Xo.<anonymous> (https://xen.serveraddress/app.js:72:24578)
    at Scope.$eval (https://xen.serveraddress/app.js:28:5228)
    at Scope.$digest (https://xen.serveraddress/app.js:28:3042)
    at Scope.$apply (https://xen.serveraddress/app.js:28:5646)
    at $$debounceViewValueCommit (https://xen.serveraddress/app.js:31:22365)
    at $setViewValue (https://xen.serveraddress/app.js:31:21821)
    at HTMLInputElement.listener (https://xen.serveraddress/app.js:29:9081)
    at HTMLInputElement.jQuery.event.dispatch (https://xen.serveraddress/app.js:56:11101)
    at HTMLInputElement.elemData.handle (https://xen.serveraddress/app.js:56:5931)
From previous event:
    at Xo.call (https://xen.serveraddress/app.js:72:24545)
    at Object.defineProperties.call (https://xen.serveraddress/app.js:12:29849)
    at Object.load (https://xen.serveraddress/app.js:14:7086)
    at _execPluginMethod (https://xen.serveraddress/app.js:7:18936)
    at toggleLoad (https://xen.serveraddress/app.js:7:19792)
    at fn (eval at <anonymous> (https://xen.serveraddress/app.js:30:14292), <anonymous>:4:316)
    at Scope.$eval (https://xen.serveraddress/app.js:28:5228)
    at https://xen.serveraddress/app.js:31:10910
    at https://xen.serveraddress/app.js:31:21657
    at forEach (https://xen.serveraddress/app.js:24:1084)
    at $$writeModelToScope (https://xen.serveraddress/app.js:31:21600)
    at writeToModelIfNeeded (https://xen.serveraddress/app.js:31:20810)
    at https://xen.serveraddress/app.js:31:21501
    at validationDone (https://xen.serveraddress/app.js:31:20212)
    at processAsyncValidators (https://xen.serveraddress/app.js:31:19998)
    at $$runValidators (https://xen.serveraddress/app.js:31:20366)
    at $$parseAndValidate (https://xen.serveraddress/app.js:31:21363)
    at $commitViewValue (https://xen.serveraddress/app.js:31:20680)
    at https://xen.serveraddress/app.js:31:22388

**Comment by julien-f** [comment]
Did you configure the plugin from the plugins page (Main menu > Settings > Plugins)?

**Comment by Phlogi** [comment]
Yes, when I try to save the configuration I get the same "invalid parameter(s)" error.

**Comment by julien-f** [comment]
Don't you have more information about the error in the browser console?

**Comment by Phlogi** [comment]
![image](https://cloud.githubusercontent.com/assets/6451003/11561796/05d09bde-99ca-11e5-8ba1-361fc7191295.png)

I did put a password into the field...

**Comment by julien-f** [comment]
Looking into it, thanks for the info.

**Comment by julien-f** [comment]
Can you check that you are using the latest version of xo-server-transport-email?
Because the password field is now named `transport.password`, not `transport.pass`.

**Comment by Phlogi** [comment]
I did npm install xo-server-transport-email@latest in xo-server folder but still get the same error.

**Comment by Phlogi** [comment]
https://github.com/vatesfr/xo-server-transport-email/compare/master...Phlogi:patch-1

**Comment by julien-f** [comment]
Thank you!

**Comment by julien-f** [comment]
Published as xo-server-tranport-email 0.0.2.

**Comment by Phlogi** [comment]
Perfect!

**Comment by Phlogi** [comment]
Works!

**Comment by olivierlambert** [comment]
Thanks for your fix @Phlogi !
