### ISSUE TITLE
Jobs vm.revert no Snapshot ID selectable on UI

### ISSUE THREAD

**Issue by maxx8888** [vatesfr/xo#85]
Jobs -> vm.revert Feature not working.

When a Job with Command "vm.revert" is executed following Error is posted within Logs:

`vm.revert
{
  "id": "5f172af3-312f-2b8c-dfd1-09228798654e",
  "snapshotBefore": false
}
{
  "message": "no such object",
  "stack": "XoError: no such object
    at factory (/root/xo-server/node_modules/xo-common/src/api-errors.js:21:26)
    at Xo.getObject (/root/xo-server/dist/xo.js:155:25)
    at /root/xo-server/dist/xo-mixins/xo-mixins/api.js:119:24
    at /root/xo-server/node_modules/lodash/_createBaseFor.js:17:11
    at baseForOwn (/root/xo-server/node_modules/lodash/_baseForOwn.js:13:20)
    at /root/xo-server/node_modules/lodash/_createBaseEach.js:17:14
    at forEach (/root/xo-server/node_modules/lodash/forEach.js:38:10)
    at Xo.resolveParams (/root/xo-server/dist/xo-mixins/xo-mixins/api.js:113:10)
    at Api._callee2$ (/root/xo-server/dist/xo-mixins/xo-mixins/api.js:257:49)
    at tryCatch (/root/xo-server/node_modules/regenerator-runtime/runtime.js:64:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/root/xo-server/node_modules/regenerator-runtime/runtime.js:355:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/root/xo-server/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/root/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /root/xo-server/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/root/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /root/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/root/xo-server/node_modules/babel-runtime/node_modules/core-js/library/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)",
  "code": 1,
  "data": {
    "id": "5f172af3-312f-2b8c-dfd1-09228798654e"
  }
} `

Most likely this is caused because Command is not containing any SnapshotName, which should be reverted to.

Background Information / Used Case:
For Schools, Training Centers, etc, it would be a very cool Feature to have a Clean VM every morning when Training starts.

That means, Administrator/Operator is adjusting VM (installing Programs, etc) to current needs. Then a Snapshot with a name like "Golden" is taken. 
A Job within Orchestra is running every night and reverting the VM back to this "golden" State.
When Trainee is arriving in the morning and connecting to the VM, a clean VM will be found again, independent what the Trainee on the last day has done with it.

Additionally, it would be even more cool when the Golden Snapshot is not containing Disks only, but also containing the Memory state. Then it would be even possible to have Trainings Programs up&running already when somebody is connecting to it.

**Comment by olivierlambert** [comment]
Please create issues there: https://github.com/vatesfr/xo-web/issues/new

As explained when you created an issue:

```
# ALL ISSUES SHOULD BE CREATED IN XO-WEB'S TRACKER!

https://github.com/vatesfr/xo-web/issues
```
