### ISSUE TITLE
Error: Command failed: losetup -D in LVM paritions

### ISSUE THREAD

**Issue by nareshn2003** [vatesfr/xo#91]
# ALL ISSUES SHOULD BE CREATED IN XO-WEB'S TRACKER!

https://github.com/vatesfr/xo-web/issues

[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[WARN] start error: Error: Command failed: losetup -D
losetup: unrecognized option: D
BusyBox v1.25.1 (2016-10-26 16:15:20 GMT) multi-call binary.

Usage: losetup [-r] [-o OFS] {-f|LOOPDEV} FILE - associate loop devices
        losetup -d LOOPDEV - disassociate
        losetup -a - show status
        losetup -f - show next free loop device

        -o OFS  Start OFS bytes into FILE
        -r      Read-only
        -f      Show/use next free loop device

    at Promise.all.then.arr (/app/xo-server/node_modules/execa/index.js:210:11)
    at tryCatcher (/app/xo-server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/xo-server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/xo-server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/xo-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/xo-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/app/xo-server/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/app/xo-server/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/app/xo-server/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/app/xo-server/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/app/xo-server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/xo-server/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/app/xo-server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/app/xo-server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/app/xo-server/node_modules/bluebird/js/release/async.js:17:14)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Tue, 13 Jun 2017 06:59:57 GMT xo:perf blocked for 52ms
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Tue, 13 Jun 2017 07:00:44 GMT xo:perf blocked for 47ms
Tue, 13 Jun 2017 07:00:55 GMT xo:perf blocked for 49ms
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
Tue, 13 Jun 2017 07:01:05 GMT xo:perf blocked for 31ms
[Warn] Unhandled error event: Error: Redis connection to redis:6379 failed - getaddrinfo EAI_AGAIN redis:6379
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

**Comment by julien-f** [comment]
1. All issues should be created in xo-web's tracker!
2. you need to have Redis installed, see the [documentation](https://xen-orchestra.com/docs/from_the_sources.html)
3. `losetup -D` error is just a warning and can be ignored.

**Comment by nareshn2003** [comment]
HI

Redis is already installed and i am runing using docker .  When i setup without LVM parition this works without any issue.
